Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: ECS单机版
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
    ModifyParametersConfig:
      - TemplateName: ECS单机版
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: ECS单机版
          Url: 'ros_templates/template.yaml'
          ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
          AllowedRegions:
            - ap-southeast-1
      ArtifactRelation:
        ecs_image_quickstart-DeepSeek-R1-Distill-Qwen-1.5B:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
    - Locale: zh-CN
      Name: aliyun-computenest/quickstart-DeepSeek-R1-Distill-Qwen-1.5B-0bij
      ShortDescription: Service description
      Image:
        https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/service-image/bfd30cc4-e959-4093-b5cb-77a05058b911.png
      SoftwareInfos: []
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_quickstart-DeepSeek-R1-Distill-Qwen-1.5B
    Description: quickstart-DeepSeek-R1-Distill-Qwen-1.5B EcsImage
    SupportRegionIds:
      - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: mengjunwei-mjw
        RepoName: aliyun-computenest/quickstart-DeepSeek-R1-Distill-Qwen-1.5B
        Branch: main
        SystemDiskSize:
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      SourceImageId:
        m-t4n4ql91gw9psd7fhxt1
      SystemDiskSize: 80
      CommandContent: |-
        git clone https://www.modelscope.cn/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B.git /root/llm-model/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
        docker pull compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/public/vllm:v0.8.2-sglang0.4.3.post2-pytorch2.6.0-cuda12.4-ubuntu22.04-ray2.44.1-erdma
